spring:
  application:
    name: epidemic-pandemic-service
  config:
    import: optional:classpath:common-config.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.100:3306/epidemic_pandemic?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  rabbitmq:
    host: 192.168.150.100
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.epidemic.pandemic.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 8083